### Listar usuarios
GET http://127.0.0.1:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI3YmNkOTIyMy0wMWI4LTRkNTctOWEzMS00YTJkMWFlZWRkMzAiLCJyb2xlcyI6WyJhZG1pbiJdLCJpYXQiOjE3NzE0NjQ4ODMsImV4cCI6MTc3MTQ2ODQ4M30.-8FyJX3Yh47Bba-IvltOAVZI30OsZo3ZItQLvlKx_hA

### Crear usuarios
POST http://127.0.0.1:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI3YmNkOTIyMy0wMWI4LTRkNTctOWEzMS00YTJkMWFlZWRkMzAiLCJyb2xlcyI6WyJhZG1pbiJdLCJpYXQiOjE3NzAyNTc1NDgsImV4cCI6MTc3MDI2MTE0OH0.Bce15Oc-VnieN8gRb0UUfO2d8BsizbYgIXtOqhj4TpU
Content-Type: application/json

{
    "username": "cristian",
    "email": "cristian@mail.com",
    "password": "cristian54321"
}

### mostrar usuario por id
GET http://127.0.0.1:3000/users/0bc29960-2829-4273-9361-404309513cf0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI3YmNkOTIyMy0wMWI4LTRkNTctOWEzMS00YTJkMWFlZWRkMzAiLCJyb2xlcyI6WyJhZG1pbiJdLCJpYXQiOjE3NzAyNTc1NDgsImV4cCI6MTc3MDI2MTE0OH0.Bce15Oc-VnieN8gRb0UUfO2d8BsizbYgIXtOqhj4TpU


### Modificar usuario por id
PATCH http://127.0.0.1:3000/users/0bc29960-2829-4273-9361-404309513cf0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI3YmNkOTIyMy0wMWI4LTRkNTctOWEzMS00YTJkMWFlZWRkMzAiLCJyb2xlcyI6WyJhZG1pbiJdLCJpYXQiOjE3NzAyNTc1NDgsImV4cCI6MTc3MDI2MTE0OH0.Bce15Oc-VnieN8gRb0UUfO2d8BsizbYgIXtOqhj4TpU
Content-Type: application/json

{
  "username": "cristian modificado",
  "email": "cristian.modificado@mail.com"
}

### ELIMINAR usuario por id
DELETE http://127.0.0.1:3000/users/d10a3b03-0051-4a1d-9a6b-e975ec50238f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI3YmNkOTIyMy0wMWI4LTRkNTctOWEzMS00YTJkMWFlZWRkMzAiLCJyb2xlcyI6WyJhZG1pbiJdLCJpYXQiOjE3NzAyNTc1NDgsImV4cCI6MTc3MDI2MTE0OH0.Bce15Oc-VnieN8gRb0UUfO2d8BsizbYgIXtOqhj4TpU

